# Jekyll Resume Theme

# Site settings
title: Jeongeun Lee
email: vcp.jeongeun@gmail.com
description: Jeongeun Lee's Portfolio
url: https://jeongeun-lee.com
baseurl: /
name: Jeongeun
full_name: Jeongeun Lee
pronunciation: [dʒʌŋ -n]
job: digital product designer or UX/UI designer
location: Tampere, Finland
languages: HTML, CSS, Javascript and JQuery
github_username:  ljeun
email_address: vcp.jeongeun@gmail.com
phone_number: +358465552105
hello_image: /img/header/hello.png
google_analytics: 'UA-32364873-2'

# Build settings
markdown: kramdown
