# Jekyll Resume Theme

# Site settings
title: Jeongeun Lee
email: vcp.jeongeun@gmail.com
description: Jeongeun Lee's Portfolio
baseurl: /portfolio
url: https://ljeun.github.io/portfolio/
name: Jeongeun
job: user experience designer
location: Tampere, Finland
languages: HTML, CSS, Javascript and JQuery
github_username:  ljeun
email_address: vcp.jeongeun@gmail.com
phone_number: +358465552105

# Build settings
markdown: kramdown
