# Jekyll Resume Theme

# Site settings
title: Jeongeun Lee
email: vcp.jeongeun@gmail.com
description: Jeongeun Lee's Portfolio
url: https://jeongeun-lee.com
name: Jeongeun
job: digital product designer or UX/UI designer
location: Tampere, Finland
languages: HTML, CSS, Javascript and JQuery
github_username:  ljeun
email_address: vcp.jeongeun@gmail.com
phone_number: +358465552105
hello_image: /img/header/hello.png

# Build settings
markdown: kramdown
